services:
  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - api1
      - api2
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  api1: &api
    image: thomazmbonfim/rinha-de-backend-2025-keydb:latest
    hostname: api1
    environment:
      - REDIS_URL=6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - API_NAME=1
    networks:
      - backend
      - payment-processor
    depends_on:
      keydb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "75MB"
  api2: 
    <<: *api
    hostname: api2
    environment:
      - REDIS_URL=6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - API_NAME=2
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "75MB"

  keydb:
    image: eqalpha/keydb:x86_64_v6.3.4
    container_name: keydb-rinha
    # O comando abaixo é opcional, mas recomendado para tuning fino.
    # '--server-threads 2' instrui o KeyDB a usar 2 threads para processar comandos,
    # aproveitando seu potencial multithread. O ideal é que seja menor ou igual ao 
    # número de CPUs disponíveis para o contêiner.
    command: >
      keydb-server /etc/keydb/keydb.conf 
      --server-threads 2 
      --maxclients 20000
    networks:
      - backend
    healthcheck:
      # CORREÇÃO: Usa 'keydb-cli' em vez de 'redis-cli'.
      test: ["CMD", "keydb-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          # O KeyDB pode se beneficiar de um pouco mais de CPU por ser multithread.
          cpus: "0.5" 
          memory: "150MB"
networks:
    backend:
      driver: bridge
    payment-processor: 
      name: payment-processor
      external: true
