services:
  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - api1
      - api2
    ports: 
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  api1: &api
    image: thomazmbonfim/rinha-2025:tag
    hostname: api1
    environment:
      - APP_PORT=8080
      - REDIS_URL=6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_health
    deploy:
      resources:
        limits:
          cpus:"0.5"
          memory:"30MB"
  api2: 
    <<: *api
    hostname: api2
    environment:
      - APP_PORT=8080
      - REDIS_URL=6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080

  redis:
    image: redis:7.2-alpine 
    container_name: redis-rinha
    command: # DEFINIR POSTERIORMENTE COMMAND
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "250MB"
  networks:
    backend:
      driver: bridge
    payment-processor: 
      external: true
